"""Safe filesystem boundary for generated project artifacts."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol


class ProjectWorkspace(Protocol):
    """Abstract file workspace used by code-generation agents."""

    def exists(self, relative_path: str) -> bool:
        """Return whether a project-relative file exists."""

    def read_text(self, relative_path: str) -> str:
        """Read UTF-8 content from a project-relative file."""

    def write_text(self, relative_path: str, content: str) -> None:
        """Atomically persist UTF-8 content to a project-relative file."""

    def is_generated(self, relative_path: str) -> bool:
        """Return whether a file is managed by the code-generation platform."""


class FileSystemProjectWorkspace:
    """Filesystem workspace that rejects paths escaping its configured root."""

    _GENERATION_MARKER = "Generated by Agentic Software Engineer"

    def __init__(self, root_directory: Path) -> None:
        """Create a workspace rooted at a caller-approved generated-project path."""
        self._root_directory = root_directory.resolve()
        self._root_directory.mkdir(parents=True, exist_ok=True)

    def exists(self, relative_path: str) -> bool:
        """Return whether the resolved project-relative file exists."""
        return self._resolve(relative_path).is_file()

    def read_text(self, relative_path: str) -> str:
        """Read UTF-8 content from a safely resolved project-relative file."""
        return self._resolve(relative_path).read_text(encoding="utf-8")

    def write_text(self, relative_path: str, content: str) -> None:
        """Persist UTF-8 file content after ensuring its parent directory exists."""
        target = self._resolve(relative_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")

    def is_generated(self, relative_path: str) -> bool:
        """Identify managed files through the platform's non-secret header marker."""
        return self.exists(relative_path) and self._GENERATION_MARKER in self.read_text(relative_path)[:512]

    def _resolve(self, relative_path: str) -> Path:
        """Resolve a path and reject traversal outside the configured workspace root."""
        candidate = (self._root_directory / relative_path).resolve()
        if candidate == self._root_directory or self._root_directory not in candidate.parents:
            raise ValueError("Generated file path escapes the configured project workspace.")
        return candidate
