"""Pathlib-based materialization of approved code-generation plans."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path, PurePath

from pydantic import BaseModel, ConfigDict, Field

from agentic_software_engineer.domain.entities.code_generation_plan import (
    CodeGenerationPlan,
    FileSpecification,
    OverwritePolicy,
)


class FileBuildResult(BaseModel):
    """Outcome for one planned generated file."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    path: str = Field(min_length=1, description="Project-relative file path.")
    action: str = Field(min_length=1, description="Created, overwritten, preserved, skipped, or approval-required.")
    detail: str = Field(min_length=1, description="Deterministic explanation of the action.")


class ProjectBuildReport(BaseModel):
    """Structured report for a project-build execution."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    project_root: str = Field(min_length=1, description="Resolved root directory for the generated project.")
    created_directories: list[str] = Field(default_factory=list, description="Directories created during the build.")
    file_results: list[FileBuildResult] = Field(default_factory=list, description="Per-file build outcomes.")
    approval_required: bool = Field(default=False, description="Whether protected existing files require human approval.")


class ProjectBuilder:
    """Create a safe generated project workspace from a ``CodeGenerationPlan``.

    Existing files are preserved by default. The builder overwrites only when the
    approved file specification explicitly permits it. All resolved paths are
    constrained to the caller-provided workspace root to prevent path traversal.
    """

    _GENERATION_MARKER = "Generated by Agentic Software Engineer"

    def __init__(self, workspace_root: Path) -> None:
        """Create a project builder rooted at a caller-approved workspace directory.

        Args:
            workspace_root: Parent directory within which generated projects may
                be created. It is resolved before use and created if missing.
        """
        self._workspace_root = workspace_root.resolve()
        self._workspace_root.mkdir(parents=True, exist_ok=True)

    def build(
        self,
        plan: CodeGenerationPlan,
        generated_contents: Mapping[str, str],
    ) -> ProjectBuildReport:
        """Create project directories and persist supplied content in generation order.

        Args:
            plan: Approved immutable generation plan.
            generated_contents: Raw file content keyed by planned relative path.

        Returns:
            Typed execution report with directory and file outcomes.

        Raises:
            ValueError: If the plan references invalid paths, content is missing,
                or supplied content includes an unplanned path.
        """
        project_root = self._project_root(plan)
        created_directories = self._create_directories(project_root, plan)
        files_by_path = {file_specification.path: file_specification for file_specification in plan.files}
        unknown_content_paths = set(generated_contents) - set(files_by_path)
        if unknown_content_paths:
            raise ValueError(f"Generated content contains unplanned files: {', '.join(sorted(unknown_content_paths))}")

        file_results: list[FileBuildResult] = []
        approval_required = False
        for relative_path in plan.generation_order:
            file_specification = files_by_path.get(relative_path)
            if file_specification is None:
                raise ValueError(f"Generation order references unknown file '{relative_path}'.")
            content = generated_contents.get(relative_path)
            if content is None:
                raise ValueError(f"Missing generated content for '{relative_path}'.")
            result = self._write_file(project_root, file_specification, content)
            file_results.append(result)
            approval_required = approval_required or result.action == "approval_required"

        return ProjectBuildReport(
            project_root=str(project_root),
            created_directories=created_directories,
            file_results=file_results,
            approval_required=approval_required,
        )

    def _project_root(self, plan: CodeGenerationPlan) -> Path:
        """Resolve the plan's project root and ensure it stays in the workspace."""
        project_root = self._resolve_within(
            self._workspace_root,
            plan.project_root,
            allow_root=True,
        )
        project_root.mkdir(parents=True, exist_ok=True)
        return project_root

    def _create_directories(self, project_root: Path, plan: CodeGenerationPlan) -> list[str]:
        """Create missing directories implied by planned generated file paths."""
        created_directories: list[str] = []
        directory_paths = sorted({str(PurePath(file.path).parent) for file in plan.files if str(PurePath(file.path).parent) != "."})
        for directory_path in directory_paths:
            target = self._resolve_within(project_root, directory_path, allow_root=True)
            if not target.exists():
                target.mkdir(parents=True, exist_ok=True)
                created_directories.append(directory_path)
        return created_directories

    def _write_file(
        self,
        project_root: Path,
        file_specification: FileSpecification,
        content: str,
    ) -> FileBuildResult:
        """Apply the approved overwrite policy and write one project-relative file."""
        target = self._resolve_within(project_root, file_specification.path)
        exists = target.is_file()
        if exists:
            if file_specification.overwrite_policy in {OverwritePolicy.NEVER, OverwritePolicy.CREATE_ONLY}:
                return FileBuildResult(path=file_specification.path, action="preserved", detail="Existing file is protected by never-overwrite policy.")
            if file_specification.overwrite_policy is OverwritePolicy.REQUIRE_APPROVAL:
                return FileBuildResult(path=file_specification.path, action="approval_required", detail="Existing file requires human approval before overwrite.")

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
        action = "merged" if exists and file_specification.overwrite_policy is OverwritePolicy.MERGE else "overwritten" if exists else "created"
        return FileBuildResult(path=file_specification.path, action=action, detail="Generated content was written successfully.")

    def _resolve_within(self, root: Path, relative_path: str, *, allow_root: bool = False) -> Path:
        """Resolve a relative path and reject paths outside the supplied root."""
        target = (root / relative_path).resolve()
        if (target == root and not allow_root) or (target != root and root not in target.parents):
            raise ValueError("Project path escapes the configured workspace root.")
        return target

    def _is_generated(self, path: Path) -> bool:
        """Identify a platform-managed file through its standard generation marker."""
        return self._GENERATION_MARKER in path.read_text(encoding="utf-8")[:512]
